startupSystem/urls.py
from django.urls import path
from . import views

app_name = 'startupsSystem'

urlpatterns = [
    path('', views.startupsList, name="startupsList"),
    path('mystartups/', views.userStartups, name="myStartups"),
    path('authorStartups/<str:username>/', views.authorStartups, name="authorStartups"),
    path('startup/<int:pk>/', views.startupDetails, name="startupDetails"),
    path('startup/observe/<int:pk>/', views.observeStartup, name="observeStartup"),
    path('startup/edit/<int:pk>/', views.editStartup, name="editStartup"),
    path('startup/unobserve/<int:pk>/', views.unobserveStartup, name="unobserveStartup"),
    path('startup/observations/<int:pk>/', views.startupObservations, name="startupObservations"),
    path('startup/delete/<int:pk>/', views.startupDelete, name="startupDelete"),
    path('createStartup/', views.createStartup, name="createStartup"),
    path('myobservations/', views.myObservations, name="myObservations"),
    path('addPictureToStartup/<int:pk>/',views.addPictureToStartup, name="addPictureToStartup"),
]

strup/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls'), name="users"),
    path('', include('startupSystem.urls'), name='startups'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('signin/', views.signUserIn, name="signIn"),
    path('signup/', views.signUserUp, name="signUp"),
    path('activate/<uidb64>/<token>', views.VerificationView.as_view(), name="activate"),
    path('dashboard/', views.getDashboard, name="dashboard"),
    path('profile/<str:username>', views.getProfile, name="profile"),
    path('signout/', views.signUserOut, name="signOut"),
    path('changeProfileData/', views.changeProfileData, name="changeProfileData"),
    path('deleteAccount/', views.deleteAccount, name="deleteAccount")
]

startupSystem/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse

class Startup(models.Model):
    author = models.ForeignKey(User, related_name="startups", on_delete=models.CASCADE)
    title = models.CharField(max_length=500)
    shortDescription = models.CharField(max_length=8000)
    createDate = models.DateField(auto_now_add=True)
    mainPhoto = models.ImageField(upload_to='startupPictures/main', blank=True)

    def url(self):
        return reverse('startupsSystem:startupDetails',args=[self.pk])

    def url_edit(self):
        return reverse('startupsSystem:editStartup',args=[self.pk])

    def url_delete(self):
        return reverse('startupsSystem:startupDelete',args=[self.pk])

    def url_observe(self):
        return reverse('startupsSystem:observeStartup',args=[self.pk])

    def url_unobserve(self):
        return reverse('startupsSystem:unobserveStartup',args=[self.pk])

    def url_observations(self):
        return reverse('startupsSystem:startupObservations',args=[self.pk])

    def url_add_image(self):
        return reverse('startupsSystem:addPictureToStartup', args=[self.pk])


class Observation(models.Model):
    observator = models.ForeignKey(User, related_name="observations", on_delete=models.CASCADE)
    startup = models.ForeignKey(Startup, related_name="startups", on_delete=models.CASCADE)
    createDate = models.DateField(auto_now_add=True)


class StartupImage(models.Model):
    startup = models.ForeignKey(Startup, related_name="images", on_delete=models.CASCADE)
    photo = models.ImageField(upload_to='startupPictures')

startupSystem/forms.py
from django import forms
from . import models

class CreateStartupForm(forms.ModelForm):
    class Meta:
        model = models.Startup
        fields = ['title','shortDescription', 'mainPhoto']
        labels = {
            'title': '',
            'shortDescription': '',
            'mainPhoto': 'Zdjęcie główne'
        }
        widgets = {
            'shortDescription': forms.Textarea(attrs={'placeholder': 'Opis startupu ', 'class':'textArea'}),
            'title': forms.TextInput(attrs={'placeholder': 'Nazwa startupu ', 'class': 'textInput'})
        }

class AddImageForm(forms.ModelForm):
    class Meta:
        model = models.StartupImage
        fields = ['photo']
        labels = {
            'photo': 'Zdjęcie'
        }

startupSystem/views.py
from django.shortcuts import render, get_object_or_404, redirect, HttpResponse
from django.contrib.auth.decorators import login_required
from .forms import CreateStartupForm, AddImageForm
from .models import Startup, Observation, StartupImage
from django.contrib.auth.models import User
from django.contrib import messages

def startupsList(request):
    startups = Startup.objects.order_by('-id')
    return render(request, 'startupsSystem/listStartups.html',{'startups': startups})

@login_required
def userStartups(request):
    startups = Startup.objects.filter(author=request.user)
    return render(request, 'startupsSystem/myStartups.html',{'startups': startups})

def startupDetails(request, pk):
    startup = get_object_or_404(Startup, pk=pk)
    images = StartupImage.objects.filter(startup=startup)
    canObserve = True
    if request.user.is_authenticated:
        if Observation.objects.filter(startup=startup, observator=request.user).exists() or startup.author == request.user:
            canObserve = False
    return render(request, 'startupsSystem/startupDetails.html',{'startup': startup, 'canObserve':canObserve, "images":images})

@login_required
def startupDelete(request, pk):
    startup = get_object_or_404(Startup, pk=pk, author=request.user)
    startup.delete()
    messages.success(request,"Pomyślnie usunięto startup.")
    return redirect('startupsSystem:myStartups')

@login_required
def createStartup(request):
    if request.method == 'POST':
        form = CreateStartupForm(request.POST, request.FILES)
        if form.is_valid():
            startup = form.save(commit=False)
            startup.author = request.user
            startup.save()
            messages.success(request, "Startup został pomyślnie utworzony.")
            return redirect('startupsSystem:myStartups')
        messages.error(request, "Nieprawidłowe dane.")
    form = CreateStartupForm()
    return render(request, 'startupsSystem/createStartup.html', {'form': form})
        
@login_required
def observeStartup(request, pk):
    user = request.user
    startup = get_object_or_404(Startup, pk=pk)
    if not Observation.objects.filter(startup=startup, observator=user).exists() and user != startup.author:
        observation = Observation.objects.create(observator = user, startup=startup)
        messages.success(request, "Pomyślnie zaobserwowano startup.")
    else:
        messages.error(request, "Nieprawidłowe dane.")
    return redirect('startupsSystem:startupDetails', pk)

@login_required
def unobserveStartup(request, pk):
    user = request.user
    startup = get_object_or_404(Startup, pk=pk)
    if Observation.objects.filter(startup=startup, observator=user).exists():
        observation = Observation.objects.filter(observator = request.user, startup=startup).delete()
        messages.success(request, "Startup przestał być przez Ciebie obserwowany.")
    else:
        messages.error(request, "Nieprawidłowe dane.")
    return redirect('startupsSystem:startupDetails', pk)

@login_required
def startupObservations(request, pk):
    startup = get_object_or_404(Startup, pk=pk)
    observations = Observation.objects.filter(startup=startup)
    return render(request, 'startupsSystem/startupObservations.html',{"observations":observations})

@login_required
def myObservations(request):
    user = request.user
    observations = Observation.objects.filter(observator=user)
    return render(request, 'startupsSystem/myObservations.html',{"observations":observations})

@login_required
def addPictureToStartup(request, pk):
    if request.method == 'POST':
        form = AddImageForm(data=request.POST, files=request.FILES)
        if form.is_valid():
            user = request.user
            startup = get_object_or_404(Startup, pk=pk, author=user)
            img = form.save(commit=False)
            img.startup = startup
            img.save()
            messages.success(request, "Pomyślnie dodano zdjęcie do startupu.")
        else:
            messages.error(request, "Nieprawidłowe dane.")
        return redirect('startupsSystem:startupDetails', pk)
    form = AddImageForm()
    return render(request, 'startupsSystem/addPictureToStartup.html', {'form':form})


def authorStartups(request, username):
    user = User.objects.get(username=username)
    startups = Startup.objects.filter(author=user)
    return render(request, 'startupsSystem/authorStartups.html', {'startups':startups, 'user':user})


@login_required
def editStartup(request, pk):
    user = request.user
    startup = get_object_or_404(Startup, pk=pk, author=user)
    if request.method == 'POST':
        form = CreateStartupForm(instance=startup,data=request.POST, files=request.FILES)
        if form.is_valid():
            form.save()
            messages.success(request, "Pomyślnie wykonano edycję startupu.")
        else:
            messages.error(request, "Nieprawidłowe dane.")
        return redirect('startupsSystem:startupDetails', pk)

    form = CreateStartupForm(instance=startup)
    return render(request, 'startupsSystem/editStartup.html', {'form':form})

startupSystem/templates/startupsSystem/addPictureToStartup.html
{% extends 'base.html' %}
{% block head %} Add picture to startup {% endblock %}

{% block content %}
<main>
    <section class="createStartupFormBox">

        <form action="." method="POST" enctype="multipart/form-data">
            <h1 class="formHeading">Dodaj zdjęcie do startupu</h1>
            {{ form }}
            {% csrf_token %}
            <input type="submit" value="Dodaj">
        </form>
    </section>

</main>
{% endblock %}

startupSystem/templates/startupsSystem/authorStartups.html
{% extends 'base.html' %}
{% load static %}
{% block head %} Startups {% endblock %}

{% block content %}

<main>

    {% if messages %}
        {% for message in messages %}
            {% if message.level == DEFAULT_MESSAGE_LEVELS.SUCCESS %}
            <div class="alert">
                <div class="title">
                    Udało się!
                </div>
                <div class="content">
                    {{ message }}
                </div>
            </div>
            {% endif %}    
        {% endfor %}
    {% endif %}



    <div class="heading">Startupy użytkownika <a href="{% url 'users:profile' user.username %}"> {{ user.username }}:</div>
    <section class="startups">

        {% for startup in startups %}
            <section class="startupItem">
                <div class="left">
                    <div class="title">
                        <a href="{{ startup.url }}">{{ startup.title }}</a>
                    </div> 
                    {% if startup.author != request.user %}
                        <div class="author">
                            <a href="{% url 'users:profile'  startup.author.username %}">
                        {% if startup.author.profile.photo %}
                            <img src="{{ startup.author.profile.photo.url }}" class="authorPhoto">
                        {% endif %} 
                        <div>{{ startup.author }}</div> </a> </div> 
                    {% endif %}
                    <div class="description"> {{ startup.shortDescription|truncatewords:75 }} </div>
                    <a href="{{ startup.url_observations }}"><i class="icon-star-empty"></i> Zobacz, kto obserwuje ten startup</a> <br>
                    {% if startup.author == request.user %}
                        <a class="delete" href="{{ startup.url_delete }}"><i class="icon-trash-empty"></i> Usuń ten startup</a>
                    {% endif %}

                </div>
                <div class="right">

                        {% if startup.mainPhoto %}
                        <img src="{{ startup.mainPhoto.url }}" class="startupPhoto" >
                        {% else %}
                        <img src="{% static './imgs/default.jpg' %}" class="startupPhoto">
                        {% endif %}

                </div>
            </section>
        {% endfor %}
    </section>
</main>
{% endblock %}

startupSystem/templates/startupsSystem/createStartup.html
{% extends 'base.html' %}
{% block head %} Create startup {% endblock %}

{% block content %}
<main>
    <section class="createStartupFormBox">

        <form action="." method="POST" enctype="multipart/form-data">
            <h1 class="formHeading">Utwórz startup</h1>
            {{ form }}
            {% csrf_token %}
            <input type="submit" value="Utwórz">
        </form>
    </section>

</main>
{% endblock %}

startupSystem/templates/startupsSystem/editStartup.html
{% extends 'base.html' %}
{% block head %} Edit startup {% endblock %}

{% block content %}
<main>
    <section class="createStartupFormBox">

        <form action="." method="POST" enctype="multipart/form-data">
            <h1 class="formHeading">Edit startup</h1>
            {{ form }}
            {% csrf_token %}
            <input type="submit" value="Confirm">
        </form>
    </section>

</main>
{% endblock %}

startupSystem/templates/startupsSystem/listStartups.html
{% extends 'base.html' %}
{% load static %}
{% block head %} Startups {% endblock %}

{% block content %}

<main>

    {% if messages %}
        {% for message in messages %}
            {% if message.level == DEFAULT_MESSAGE_LEVELS.SUCCESS %}
            <div class="alert">
                <div class="title">
                    Udało się!
                </div>
                <div class="content">
                    {{ message }}
                </div>
            </div>
            {% endif %}    
        {% endfor %}
    {% endif %}



    <div class="heading">Startupy</div>
    <section class="startups">

        {% for startup in startups %}
            <section class="startupItem">
                <div class="left">
                    <div class="title">
                        <a href="{{ startup.url }}">{{ startup.title }}</a>
                    </div> 
                    {% if startup.author != request.user %}
                        <div class="author">
                            <a href="{% url 'users:profile'  startup.author.username %}">
                        {% if startup.author.profile.photo %}
                            <img src="{{ startup.author.profile.photo.url }}" class="authorPhoto">
                        {% endif %} 
                        <div>{{ startup.author }}</div> </a> </div> 
                    {% endif %}
                    <div class="description"> {{ startup.shortDescription|truncatewords:75 }} </div>
                    <a href="{{ startup.url_observations }}"><i class="icon-star-empty"></i> Zobacz, kto obserwuje ten startup</a> <br>
                    {% if startup.author == request.user %}
                        <a class="delete" href="{{ startup.url_delete }}"><i class="icon-trash-empty"></i> Usuń ten startup</a>
                    {% endif %}

                </div>
                <div class="right">

                        {% if startup.mainPhoto %}
                        <img src="{{ startup.mainPhoto.url }}" class="startupPhoto" >
                        {% else %}
                        <img src="{% static './imgs/default.jpg' %}" class="startupPhoto">
                        {% endif %}

                </div>
            </section>
        {% endfor %}
    </section>
</main>
{% endblock %}

startupSystem/templates/startupsSystem/myObservations.html
{% extends 'base.html' %}
{% load static %}
{% block head %} Startups {% endblock %}

{% block content %}
<main>
    {% if messages %}
        {% for message in messages %}
            {% if message.level == DEFAULT_MESSAGE_LEVELS.SUCCESS %}
            <div class="alert">
                <div class="title">
                    Udało się!
                </div>
                <div class="content">
                    {{ message }}
                </div>
            </div>
            {% endif %}    
        {% endfor %}
    {% endif %}
    <div class="heading">Zapisane startupy</div>
    <section class="startups">

        {% for observation in observations %}
            <section class="startupItem">
                <div class="left">
                    <div class="title">
                        <a href="{{ observation.startup.url }}">{{ observation.startup.title }}</a>
                    </div> 
                    {% if observation.startup.author != request.user %}
                        <div class="author">
                            <a href="{% url 'users:profile'  observation.startup.author.username %}">
                        {% if startup.author.profile.photo %}
                            <img src="{{ observation.startup.author.profile.photo.url }}" class="authorPhoto">
                        {% endif %} 
                        <div>{{ observation.startup.author }}</div> </a> </div> 
                    {% endif %}
                    <div class="description"> {{ observation.startup.shortDescription|truncatewords:75 }} </div>
                    <a href="{{ observation.startup.url_observations }}"><i class="icon-star-empty"></i> Zobacz, kto obserwuje ten startup</a> <br>
                    {% if observation.startup.author == request.user %}
                        <a class="delete" href="{{ startup.url_delete }}"><i class="icon-trash-empty"></i> Usuń ten startup</a>
                    {% endif %}

                </div>
                <div class="right">

                        {% if observation.startup.mainPhoto %}
                        <img src="{{ observation.startup.mainPhoto.url }}" class="startupPhoto" >
                        {% else %}
                        <img src="{% static './imgs/default.jpg' %}" class="startupPhoto">
                        {% endif %}

                </div>
            </section>
        {% endfor %}
    </section>

</main>
{% endblock %}

startupSystem/templates/startupsSystem/myStartups.html
{% extends 'base.html' %}
{% load static %}
{% block head %} Startups {% endblock %}

{% block content %}
<main>

    {% if messages %}
        {% for message in messages %}
            {% if message.level == DEFAULT_MESSAGE_LEVELS.SUCCESS %}
            <div class="alert">
                <div class="title">
                    Udało się!
                </div>
                <div class="content">
                    {{ message }}
                </div>
            </div>
            {% endif %}    
        {% endfor %}
    {% endif %}


    <div class="heading">Moje Startupy</div>
    <section class="startups">

        {% for startup in startups %}
            <section class="startupItem">
                <div class="left">
                    <div class="title">
                        <a href="{{ startup.url }}">{{ startup.title }}</a>
                    </div> <br>
                    <div class="description"> {{ startup.shortDescription|truncatewords:75 }} </div>
                    <a href="{{ startup.url_observations }}"><i class="icon-star-empty"></i> Zobacz, kto obserwuje ten startup</a> <br>
                    <a class="delete" href="{{ startup.url_delete }}"><i class="icon-trash-empty"></i> Usuń ten startup</a>

                </div>
                <div class="right">
                    {% if startup.mainPhoto %}
                        <img src="{{ startup.mainPhoto.url }}" class="startupPhoto" > <br>
                    {% else %}
                        <img src="{% static './imgs/default.jpg' %}" class="startupPhoto">
                    {% endif %}

                </div>
            </section>
        {% endfor %}
    </section>
</main>
{% endblock %}

startupSystem/templates/startupsSystem/startupDetails.html
{% extends 'base.html' %}
{% load static %}
{% block head %} Startup  {% endblock %}

{% block content %}
<main>

    {% if messages %}
        {% for message in messages %}
            {% if message.level == DEFAULT_MESSAGE_LEVELS.SUCCESS %}
            <div class="alert">
                <div class="title">
                    Udało się!
                </div>
                <div class="content">
                    {{ message }}
                </div>
            </div>
            {% endif %}    
        {% endfor %}
    {% endif %}
    <div class="heading"> {{ startup.title }} </div>
    <section class="startup">

        {% if startup.mainPhoto %}
            <img src="{{ startup.mainPhoto.url }}" class="startupPhoto">
        {% else %}
            <img src="{% static './imgs/default.jpg' %}" class="startupPhoto">
        {% endif %}


        {% if startup.author != request.user %}
            <div class="startupAuthor">
                <a href="{% url 'users:profile' startup.author.username %}"> {{ startup.author }} </a>
            </div>
        {% endif %}

        <p> {{ startup.shortDescription }} </p>


        <section class="images">

            {% for image in images %}

                <img src="{{ image.photo.url }}"> <br>
            {% endfor %}
        </section>

        {% if request.user.is_authenticated %} <br>
            {% if canObserve %}
                <a href="{{ startup.url_observe }}" class="startupLink">
                    <div class="linkBox"><i class="icon-star"></i> Obserwuj ten startup</div>
                </a>
            {% elif request.user != startup.author %}
                <a href="{{ startup.url_unobserve }}" class="startupLink">
                    <div class="linkBox"><i class="icon-star-empty"></i> Przestań obserwować ten startup</div>
                </a>
            {% endif %}
        {% endif %}

            <a href="{{ startup.url_observations }}" class="startupLink">
                <div class="linkBox"><i class="icon-eye"></i> Zobacz, kto obserwuje ten startup</div>
            </a>
            {% if startup.author == request.user %} <br>
                <a href="{{ startup.url_add_image }}" class="startupLink">
                    <div class="linkBox"><i class="icon-plus"></i> Dodaj zdjęcie do startupu</div>
                </a>
                <a href="{{ startup.url_edit }}" class="startupLink">
                    <div class="linkBox"><i class="icon-pencil-1"></i> Edytuj ten startup</div>
                </a>
                <a href="{{ startup.url_delete }}" class="startupLink remove">
                    <div class="linkBox"><i class="icon-trash-empty"></i> Usuń ten startup</div>
                </a>
            {% endif %}
        </section>
    </main>
{% endblock %}

startupSystem/templates/startupsSystem/startupObservations.html
{% extends 'base.html' %}
{% block head %} Startups {% endblock %}

{% block content %}
<main>

    {% if messages %}
        {% for message in messages %}
            {% if message.level == DEFAULT_MESSAGE_LEVELS.SUCCESS %}
            <div class="alert">
                <div class="title">
                    Udało się!
                </div>
                <div class="content">
                    {{ message }}
                </div>
            </div>
            {% endif %}    
        {% endfor %}
    {% endif %}
    <div class="heading">Zapisany przez </div>
    <section class="observators">
        
        {% for observation in observations %}<a href="{% url 'users:profile' observation.observator.username %}">
            <section class="observator">
                <div class="left">
                    {{ observation.observator }} <br>
                </div>
                <div class="right">
                    {% if observation.observator.profile.photo %}
                    <img src="{{ observation.observator.profile.photo.url }}">
                    {% endif %}
                </div>
            </section>
            </a>
        {% endfor %}
    </section>
</main>
{% endblock %}