startupSystem/urls.py
from django.urls import path
from . import views

app_name = 'startupsSystem'

urlpatterns = [
    path('', views.startupsList, name="startupsList"),
    path('mystartups/', views.userStartups, name="myStartups"),
    path('authorStartups/<str:username>/', views.authorStartups, name="authorStartups"),
    path('startup/<int:pk>/', views.startupDetails, name="startupDetails"),
    path('startup/observe/<int:pk>/', views.observeStartup, name="observeStartup"),
    path('startup/edit/<int:pk>/', views.editStartup, name="editStartup"),
    path('startup/unobserve/<int:pk>/', views.unobserveStartup, name="unobserveStartup"),
    path('startup/observations/<int:pk>/', views.startupObservations, name="startupObservations"),
    path('startup/delete/<int:pk>/', views.startupDelete, name="startupDelete"),
    path('createStartup/', views.createStartup, name="createStartup"),
    path('myobservations/', views.myObservations, name="myObservations"),
    path('addPictureToStartup/<int:pk>/',views.addPictureToStartup, name="addPictureToStartup"),
]

strup/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls'), name="users"),
    path('', include('startupSystem.urls'), name='startups'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('signin/', views.signUserIn, name="signIn"),
    path('signup/', views.signUserUp, name="signUp"),
    path('activate/<uidb64>/<token>', views.VerificationView.as_view(), name="activate"),
    path('dashboard/', views.getDashboard, name="dashboard"),
    path('profile/<str:username>', views.getProfile, name="profile"),
    path('signout/', views.signUserOut, name="signOut"),
    path('changeProfileData/', views.changeProfileData, name="changeProfileData"),
    path('deleteAccount/', views.deleteAccount, name="deleteAccount")
]

users/models.py
from django.db import models
from django.conf import settings

class Profile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="profile")
    photo = models.ImageField(upload_to='profilePictures', blank=True)
    name = models.CharField(max_length=255, blank=True)
    surname = models.CharField(max_length=255, blank=True)

    

users/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Profile

class LoginForm(forms.Form):
    username = forms.CharField(label="",widget=forms.TextInput(attrs={'placeholder': 'Nazwa użytkownika', 'class':'textInput'}))
    password = forms.CharField(label="",widget=forms.PasswordInput(attrs={'placeholder': 'Hasło', 'class':'passwordInput'}))

class RegistrationForm(forms.ModelForm):
    password = forms.CharField(label='',widget=forms.PasswordInput(attrs={'placeholder': 'Hasło', 'class':'passwordInput'}))
    password2 = forms.CharField(label='',widget=forms.PasswordInput(attrs={'placeholder': 'Powtórz hasło', 'class':'passwordInput'}))

    class Meta:
        model = User
        fields = ('email', 'username')
        labels = {
            'email': '',
            'username': ''
        }
        widgets = {
            'email': forms.EmailInput(attrs={'placeholder': 'Adres email', 'class':'emailInput'}),
            'username': forms.TextInput(attrs={'placeholder': 'Nazwa użytkownika', 'class': 'textInput'})
        }
    
    def clean_password2(self):
        cd = self.cleaned_data
        if cd['password'] != cd['password2']:
            raise forms.ValidationError("Hasła nie są identyczne.")
        return cd['password2']

class EditProfileDataForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('photo','name', 'surname')
        labels = {
            'photo': 'Zdjęcie',
            'name': '', 
            'surname': '',

        }
        widgets = {
            'name': forms.TextInput(attrs={'placeholder': 'Imię', 'class': 'textInput'}),
            'surname': forms.TextInput(attrs={'placeholder': 'Nazwisko', 'class': 'textInput'})
        }

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.decorators import login_required
from django.core.mail import EmailMessage
from .forms import LoginForm, RegistrationForm, EditProfileDataForm
from django.conf import settings
from django.urls import reverse
from django.views import View
from django.utils.http import urlsafe_base64_encode,  urlsafe_base64_decode
from django.utils.encoding import force_bytes, force_str, DjangoUnicodeDecodeError
from django.contrib.sites.shortcuts import get_current_site
from .utils import token_generator
from .models import Profile
from django.contrib.auth.models import User
from django.contrib import messages

# ------------------------LOGIN VIEW -------------------------
def signUserIn(request):
    if request.user.is_authenticated:
        return redirect('users:dashboard')
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            user = authenticate(username=cd['username'], password=cd['password'])
            if user is not None:
                if user.is_active:
                    login(request,user)
                    messages.success(request, "Pomyślnie zalogowano.")
                    return redirect('users:dashboard')
        messages.error(request, "Błędny login lub hasło.")

    form = LoginForm()
    return  render(request, 'users/signIn.html', {'form':form})


# ------------------DAHSBOARD VIEW---------------------
@login_required
def getDashboard(request):
    user = request.user
    profile = Profile.objects.get(user=user)
    return render(request, 'users/dashboard.html', {'user':user,"profile":profile})


# -----------------------LOGOUT VIEW--------------------
@login_required
def signUserOut(request):
    logout(request)
    messages.success(request, "Pomyślnie wylogowano.")
    return redirect('users:signUp')


# ------------------REGISTER VIEW--------------------
def signUserUp(request):
    if request.user.is_authenticated:
        return redirect('users:dashboard')
    if request.method == 'POST':
        user_form = RegistrationForm(request.POST)
        if user_form.is_valid():
            user = user_form.save(commit=False)
            user.set_password(user_form.cleaned_data['password'])
            user.is_active = False
            user.save()
            profile = Profile.objects.create(user=user)
            uidb64 = urlsafe_base64_encode(force_bytes(user.pk))
            domain = get_current_site(request).domain
            link = reverse('users:activate',kwargs={'uidb64':uidb64, 'token':token_generator.make_token(user)})
            url_activate = 'http://'+domain+link
            email_body = 'Witaj ' + user.username + ', kliknij w link, aby aktywować swoje konto: '+url_activate
            mail = EmailMessage(
                "Link aktywacyjny do konta na strup",
                email_body,
                settings.EMAIL_HOST_USER,
                (user.email,)
            )
            mail.send()
            messages.success(request, "Gratulacje, proces rejestracji przeszedł pomyślnie. Potwierdź teraz swoje konto, klikając w link aktywacyjny, który dostarczyliśmy Ci pocztą na wskazany przez Ciebie adres e-mail.")
            return redirect('users:dashboard')
        else:
            messages.error(request, "Nieprawidłowe dane rejestracji.")
    else:
        user_form = RegistrationForm()
    return render(request, 'users/signUp.html', {'user_form':user_form})


# -----------------------ACTIVATE USERS --------------------------------
class VerificationView(View):
    def get(self, request, uidb64, token):
        try:
            uid = force_str(urlsafe_base64_decode(uidb64))
            user = User.objects.get(pk=uid)
        except(TypeError, ValueError, OverflowError, User.DoesNotExist, DjangoUnicodeDecodeError):
            user = None
        if user is not None and token_generator.check_token(user, token):
            user.is_active = True
            user.save()
            messages.success(request, "Weryfikacja zakończona. Teraz możesz się zalogować.")
        else:
            messages.error(request, "Błędne dane weryfikacji.")
        return redirect('users:signIn')


# -----------------------DELETE USER --------------------------------
@login_required
def deleteAccount(request):
    user = User.objects.get(pk=request.user.pk)
    logout(request)
    user.delete()
    messages.success(request, "Konto zostało pomyślnie usunięte. ")
    return redirect('users:signUp')


# -----------------------CHANGE USER IMAGE --------------------------------
@login_required
def changeProfileData(request):
    if request.method == 'POST':
        form = EditProfileDataForm(instance=request.user.profile, data=request.POST, files=request.FILES)
        if form.is_valid():
            profile = form.save(commit=False)
            profile.user = request.user
            profile.save()
            messages.success(request, "Dane zostały pomyślnie zmienione.")
        else:
            messages.error(request, "Nieprawidłowe dane.")
        return redirect('users:dashboard')
    form = EditProfileDataForm(instance=request.user.profile)
    return render(request, 'users/changeProfileData.html', {'form':form})


# -----------------------USER PROFILE --------------------------------
def getProfile(request, username):
    user = User.objects.get(username=username)
    if user == request.user:
        return redirect('users:dashboard')
    profile = Profile.objects.get(user=user)
    return render(request, 'users/profile.html', {'user':user,"profile":profile})

users/templates/users/changeProfileData.html
{% extends 'base.html' %}
{% block head %} Edit profile {% endblock %}

{% block content %}
<main>
    <section class="profileEditFormBox">

        <form action="." method="POST" enctype="multipart/form-data">
            <h1 class="formHeading">Edycja profilu</h1>
            {{ form }}
            {% csrf_token %}
            <input type="submit" value="Dalej">
        </form>
    </section>

</main>
{% endblock %}

users/templates/users/dashboard.html
{% extends 'base.html' %}
{% load static %}
{% block head %}
    Twój profil
{% endblock %}
{% block content %}
    <main>
        {% if messages %}
        {% for message in messages %}
            {% if message.level == DEFAULT_MESSAGE_LEVELS.SUCCESS %}
            <div class="alert">
                <div class="title">
                    Udało się!
                </div>
                <div class="content">
                    {{ message }}
                </div>
            </div>
            {% endif %}    
        {% endfor %}
    {% endif %}
    <section class="userData">
        <div class="left">
            <div class="userName">
                {{ user.username }}
            </div>
            <div class="userDetail">
                <div class="name">
                    {{ profile.name }}
                </div>
                <div class="surname">
                    {{ profile.surname }}
                </div>
            </div>
            <a href="{% url 'startupsSystem:myStartups' %}" class="dashboardLink">
                <div class="linkBox"><i class="icon-pencil-alt"></i> Moje Startupy</div>
            </a><a href="{% url 'startupsSystem:myObservations' %}" class="dashboardLink">
                <div class="linkBox"><i class="icon-star"></i> Zapisane startupy</div>
            </a><a href="{% url 'users:changeProfileData' %}" class="dashboardLink">
                <div class="linkBox"><i class="icon-pencil-1"></i> Edytuj swój profil</div>
            </a><a href="{% url 'users:deleteAccount' %}" class="dashboardLink">
                <div class="linkBox deleteAccount"><i class="icon-trash-empty"></i> Usuń konto</div>
            </a>
        </div>
        <div class="right">
            {% if profile.photo %}
            <img src="{{ profile.photo.url }}" >
            {% else %}
            <img src="{% static './imgs/defaultProfileImage.jpg' %}">
            {% endif %}
        </div>
    </section>
    </main>
{% endblock %}

users/templates/users/profile.html
{% extends 'base.html' %}
{% load static %}
{% block head %}
    Profil
{% endblock %}
{% block content %}
    <main>
        {% if messages %}
        {% for message in messages %}
            {% if message.level == DEFAULT_MESSAGE_LEVELS.SUCCESS %}
            <div class="alert">
                <div class="title">
                    Udało się!
                </div>
                <div class="content">
                    {{ message }}
                </div>
            </div>
            {% endif %}    
        {% endfor %}
    {% endif %}
    <section class="userData">
        <div class="left">
            <div class="userName">
                {{ user.username }}
            </div>
            <div class="userDetail">
                <div class="name">
                    {{ profile.name }}
                </div>
                <div class="surname">
                    {{ profile.surname }}
                </div>
            </div>
            <a href="{% url 'startupsSystem:authorStartups' user.username %}" class="dashboardLink">
                <div class="linkBox"><i class="icon-pencil-alt"></i> Startupy użytkownika</div>
            </a>
        </div>
        <div class="right">
            {% if profile.photo %}
            <img src="{{ profile.photo.url }}" >
            {% else %}
            <img src="{% static './imgs/defaultProfileImage.jpg' %}">
            {% endif %}
        </div>
    </section>
    </main>
{% endblock %}

users/templates/users/signIn.html
{% extends 'base.html' %}
{% block head %}
    Sign in
{% endblock %}
{% block content %}
<main>
    <section class="signInFormBox">
        <form action="." method="POST">
            <h1 class="formHeading">Zaloguj się</h1>
            {{ form }}
            {% csrf_token %}
            <input type="submit" value="Zaloguj się">
        </form>
            {% if messages %}
                {% for message in messages %}
                    {% if message.level == DEFAULT_MESSAGE_LEVELS.SUCCESS %}
                        <script>
                            swal({
                                title:"Gratulacje!",
                                text:"Potwierdź swoje konto, klikając w link aktywacyjny, który dostarczyliśmy Ci pocztą na wskazany przez Ciebie adres e-mail.",
                                icon:"success",
                                button: "Dalej" });
                        </script>
                    {% else %}
                        <p style="color: red;">{{ message }}</p>
                    {% endif %}
                {% endfor %}
            {% endif %}
        <div class="registerOption">
            <a href="{% url 'users:signUp' %}">
            lub zarejestruj się...</a>
        </div>
    </section>
</main>
{% endblock %}

users/templates/users/signUp.html
{% extends 'base.html' %}
{% block head %}
    Sign up
{% endblock %}
{% block content %}
    <main>
        <section class="signUpFormBox">
            <form action="." method="POST">
                <h1 class="formHeading">Zarejestruj się</h1>
                {{ user_form.email }}
                {{ user_form.username }}
                {{ user_form.password }}
                {{ user_form.password2 }}
                {% csrf_token %}
                <input type="submit" value="Zarejestruj się">
            </form>
            {% if messages %}
                {% for message in messages %}
                    {% if message.level == DEFAULT_MESSAGE_LEVELS.SUCCESS %}
                        <script>
                            swal({
                                title:"Udało się!",
                                text:"Pomyślnie wylogowano.",
                                icon:"success",
                                button: "Dalej" });
                        </script>
                    {% else %}
                        <p style="color: red;">{{ message }}</p>
                    {% endif %}
                {% endfor %}
            {% endif %}
            <div class="registerOption">
                <a href="{% url 'users:signIn' %}">
                </br>lub zaloguj się...</a>
            </div>
        </section>
    </main>
{% endblock %}