startupSystem/urls.py
from django.urls import path
from . import views

app_name = 'startupsSystem'

urlpatterns = [
    path('', views.startupsList, name="startupsList"),
    path('mystartups/', views.userStartups, name="myStartups"),
    path('authorStartups/<str:username>/', views.authorStartups, name="authorStartups"),
    path('startup/<int:pk>/', views.startupDetails, name="startupDetails"),
    path('startup/observe/<int:pk>/', views.observeStartup, name="observeStartup"),
    path('startup/edit/<int:pk>/', views.editStartup, name="editStartup"),
    path('startup/unobserve/<int:pk>/', views.unobserveStartup, name="unobserveStartup"),
    path('startup/observations/<int:pk>/', views.startupObservations, name="startupObservations"),
    path('startup/delete/<int:pk>/', views.startupDelete, name="startupDelete"),
    path('createStartup/', views.createStartup, name="createStartup"),
    path('myobservations/', views.myObservations, name="myObservations"),
    path('addPictureToStartup/<int:pk>/',views.addPictureToStartup, name="addPictureToStartup"),
]

strup/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls'), name="users"),
    path('', include('startupSystem.urls'), name='startups'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('signin/', views.signUserIn, name="signIn"),
    path('signup/', views.signUserUp, name="signUp"),
    path('activate/<uidb64>/<token>', views.VerificationView.as_view(), name="activate"),
    path('dashboard/', views.getDashboard, name="dashboard"),
    path('profile/<str:username>', views.getProfile, name="profile"),
    path('signout/', views.signUserOut, name="signOut"),
    path('changeProfileData/', views.changeProfileData, name="changeProfileData"),
    path('deleteAccount/', views.deleteAccount, name="deleteAccount")
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static './style/main.css' %}">
    <link rel="stylesheet" href="{% static './style/fontello/css/fontello.css' %}">
    <title>
        {% block head %}
        {% endblock %} - strup
    </title>
</head>
<body>
        <header class="siteNavBar">
            <div class="menuIcon">
                <a href=""><img src="{% static './imgs/icon/white_icon.png' %}" alt="strup" class="menuIconImg"></a>
            </div>

            <div class="menuList" id="menuBtn">
                <div class="iconBox">
                    <div class="belt"></div>
                    <div class="belt"></div>
                    <div class="belt"></div>
                </div>
            </div>
        </header>
        <nav class="mobileNav" id="mobileMenu">
            <i class="arrowRight icon-right-open-big" id="closeMenuBtn"></i>
            <ul class="mobileNavList">
                <a href="{% url 'startupsSystem:startupsList' %}"><li class="mobileNavItem"><i class="icon-lightbulb"></i> Startupy</li></a>

                
                <a href="{% url 'startupsSystem:createStartup' %}"><li class="mobileNavItem"><i class="icon-plus"></i> Utwórz nowy startup</li></a>
                
                {% if request.user.is_authenticated %}
                    <a href="{% url 'users:dashboard' %}"><li class="mobileNavItem"><i class="icon-torso"></i> Mój profil </li></a>

                    <a href="{% url 'startupsSystem:myStartups' %}"><li class="mobileNavItem"><i class="icon-pencil-alt"></i> Moje startupy</li></a>

                    <a href="{% url 'startupsSystem:myObservations' %}"><li class="mobileNavItem"><i class="icon-star"></i> Zapisane startupy</li></a>
                {% endif %}
                {% if request.user.is_authenticated %}
                    <a href="{% url 'users:signOut' %}"><li class="mobileNavItem"><i class="icon-logout"></i> Wyloguj się</li></a>
                    {% else %}
                    <a href="{% url 'users:signIn' %}"><li class="mobileNavItem"><i class="icon-login-1"></i> Zaloguj się </li></a>

                    <a href="{% url 'users:signUp' %}"><li class="mobileNavItem"><i class="icon-login-1"></i> Zarejestruj się</li></a>
                {% endif %}
            </ul>
        </nav>
        <script src="{% static './button.js' %}"></script>
        <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/gsap/3.10.4/gsap.min.js" integrity="sha512-VEBjfxWUOyzl0bAwh4gdLEaQyDYPvLrZql3pw1ifgb6fhEvZl9iDDehwHZ+dsMzA0Jfww8Xt7COSZuJ/slxc4Q==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
        {% block content %}
        {% endblock %}
    
</body>
</html>